{{- if eq .Values.fsm.trafficInterceptionMode "ebpf" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fsm-interceptor
  namespace: {{ include "fsm.namespace" . }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
    app: fsm-interceptor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fsm-interceptor
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
    app: fsm-interceptor
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - get
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fsm-interceptor
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
    app: fsm-interceptor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fsm-interceptor
subjects:
- kind: ServiceAccount
  name: fsm-interceptor
  namespace: fsm-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fsm-interceptor
  namespace: {{ include "fsm.namespace" . }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
    app: fsm-interceptor
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: fsm-interceptor
  template:
    metadata:
      labels:
        app: fsm-interceptor
    spec:
      {{- if .Values.fsm.fsmInterceptor.affinity }}
      affinity:
      {{- toYaml .Values.fsm.fsmInterceptor.affinity | nindent 8 }}
      {{- end }}
      hostNetwork: true
      containers:
      - name: fsm-interceptor
        image: "{{ include "fsmInterceptor.image" . }}"
        imagePullPolicy: {{ .Values.fsm.image.pullPolicy }}
        command: ['/app/fsm-interceptor']
        args: [
          "--verbosity", "{{.Values.fsm.controllerLogLevel}}",
          "--fsm-namespace", "{{ include "fsm.namespace" . }}",
          "--fsm-version", "{{ .Chart.AppVersion }}",
          "--mesh-name", "{{.Values.fsm.meshName}}",
          "--trust-domain", "{{.Values.fsm.trustDomain}}",
          "--cni-mode={{ .Values.fsm.fsmInterceptor.cniMode }}",
          "--kind={{ .Values.fsm.fsmInterceptor.kindMode }}",
          "--kernel-tracing={{ .Values.fsm.fsmInterceptor.kernelTracing }}",
        ]
        lifecycle:
          preStop:
            exec:
              command:
              - make
              - -k
              - clean
        resources:
          limits:
            cpu: "{{.Values.fsm.fsmInterceptor.resource.limits.cpu}}"
            memory: "{{.Values.fsm.fsmInterceptor.resource.limits.memory}}"
          requests:
            cpu: "{{.Values.fsm.fsmInterceptor.resource.requests.cpu}}"
            memory: "{{.Values.fsm.fsmInterceptor.resource.requests.memory}}"
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /sys/fs/cgroup
            name: sys-fs-cgroup
          - mountPath: /host/opt/cni/bin
            name: cni-bin-dir
          - mountPath: /host/etc/cni/net.d
            name: cni-config-dir
          - mountPath: /host/proc
            name: host-proc
          - mountPath: /host/var/run
            name: host-var-run
            mountPropagation: Bidirectional
      dnsPolicy: ClusterFirst
      priorityClassName: system-node-critical
      restartPolicy: Always
      serviceAccount: fsm-interceptor
      serviceAccountName: fsm-interceptor
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - operator: Exists
      volumes:
      - hostPath:
          path: /sys/fs/cgroup
        name: sys-fs-cgroup
      - hostPath:
          path: /proc
        name: host-proc
      - hostPath:
          #path: /opt/cni/bin
          path: /bin
        name: cni-bin-dir
      - hostPath:
          #path: /etc/cni/net.d
          path: /var/lib/rancher/k3s/agent/etc/cni/net.d
        name: cni-config-dir
      - hostPath:
          path: /var/run
        name: host-var-run
{{- end }}